### ISSUE TITLE
Redis running full after update

### ISSUE THREAD

**Issue by bastianb-yl** [prebid/prebid-cache#105]
We were running prebid cache 0.13.0 and tried an update. But after updating to 0.14.0 our redis (elasticache) is getting full after about an hour. Normally we are at about 30% capacity max.
I tried updating one commit at a time and the one that breaks it is this one: https://github.com/prebid/prebid-cache/pull/89

As far as i understand, the expiration parameter for redis is replaced with config.request_limits.max_ttl_seconds, but will still work, since the lower of the two values is used. The desired expiration time is 10 minutes, so i tried setting this, using both parameters, using config.request_limits.max_ttl_seconds without config.backend.redis.expiration, setting one lower than the other, but the result is always the same. The redis starts filling up and when it reaches 100%, the cache hit rate collapses.

Am i misconfiguring something? This is the config that works on 0.13.0:

`port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: false
  num_requests: 100
request_limits:
  allow_setting_keys: false
  max_size_bytes: 40960
  max_num_values: 10000
  max_ttl_seconds: 3600
backend:
  type: "redis"
  redis:
    host: "censored"
    port: 6379
    password: "censored"
    db: 1
    expiration: 10
compression:
  type: "snappy"
metrics:
  type: "none"`

**Comment by guscarreon** [comment]
@bastianb-yl thank you for raising this issue. After a number of tests using `redis-cli` version `5.0.7` I wasn't able to reproduce your results even when using the exact same configuration you shared. A couple of questions:
 - Is it possible there's a backend configuration issue? What version of ElastiCache are you using?
 - Have you tried updating to Prebid Cache `0.16.0`? It's the latest stable version of Prebid Cache and a number of improvements, library updates, and bug fixes have been implemented since version `0.14.0`.
 - Have you connected metrics? Starting version 0.15.1 the time-to-live per request is accounted for in the metrics. Prebid Cache supports both InfluxDB and Prometheus. 

Please let us know your thoughts

**Comment by bastianb-yl** [comment]
I tried redis versions 5.0.6 and 6.2.5
I tried every update since 0.13.0

But i found the problem. It's the put function in the redis backend (line 37).
Since keys in redis didn't expire anymore (at least 90-95%), i added some logging to see what ttl is being set. In 90-95% of all keys, the ttl is set to 0. For the rest it's 180. Which is also weird, since my ttl in the config is 600. No idea how this happens.
But if i hardcode 600 into that line, it works. I don't know yet why this is happening, but for the moment it's working again.

**Comment by guscarreon** [comment]
Interesting. We couldn't find a problem in there. We added a bunch of log entries here and there and when doing this:
```
35   // When key already holds a value, no operation is performed. That's the reason this adapter
36   // uses the 'github.com/go-redis/redis's library SetNX. SetNX is short for "SET if Not eXists".
37   func (db RedisDBClient) Put(key string, value string, ttlSeconds int) (bool, error) {
38 -     return db.client.SetNX(key, value, time.Duration(ttlSeconds)*time.Second).Result()
   +     ttlDuration := time.Duration(ttlSeconds) * time.Second
   +     log.Infof("Time-to-live in duration format: %v", ttlDuration)
   +     return db.client.SetNX(key, value, ttlDuration).Result()
39   }
backends/redis.go
```
We seem to be passing the right duration to the Redis client as asserted in the log entry below:
```
INFO[0080] time-to-live in duration format: 10m0s
```
In order to hardcode it did you do `600 * time.Second`? Was the TTL corroboration done on the server side? If not, how were the 0 and 180 TTL values found?

**Comment by guscarreon** [comment]
I believe we should also clarify that the `redis-cli` server version `5.0.7`, that we used to try to replicate this error, correctly pulled down the record after its TTL expired. We hit a local instance of Prebid-Cache using `redis-cli` as backend storage:
```
{
  "puts": [
     {
       "type": "xml",
       "ttlseconds": 10,
       "value": "<XML>data</XML>"
     }
  ]
}
~/Documents/ttl_exemplary.json
```
With a running instance of Prebid Cache and `redis-cli` we put and get before the expiration time of 10 seconds:
```
~/Documents$ curl -d@ttl_exemplary.json http://localhost:2424/cache
{"responses":[{"uuid":"dde24647-e98a-48a7-a675-3f12a54a18f8"}]}

~/Documents$ curl http://localhost:2424/cache?uuid=dde24647-e98a-48a7-a675-3f12a54a18f8
<XML>data</XML>
```
After waiting a bit longer for the 10 seconds to expire:
```
~/Documents$ curl http://localhost:2424/cache?uuid=dde24647-e98a-48a7-a675-3f12a54a18f8
GET /cache uuid=dde24647-e98a-48a7-a675-3f12a54a18f8: Key not found
```
Log entries for test:
```
INFO[1894] Redis backend will store for 10 seconds      
INFO[1894] time-to-live in duration format: 10s  
```
Are we sure elasticache is fully compatible with the current Redis golang client Prebid Cache supports?

**Comment by bastianb-yl** [comment]
Try removing the ttlSeconds from your json. If i do that with version 0.13.0 you should get the value from the config. With 0.17.0, it should be 0.

**Comment by guscarreon** [comment]
Amazing find @bastianb-yl that's definitely a bug that went over our heads in the most recent changes implemented to Prebid Cache. Pull request #107 has been created to address and correct this problem.

**Comment by bastianb-yl** [comment]
Great, thank you very much.
