### ISSUE TITLE
Restrict access to POST method

### ISSUE THREAD

**Issue by bradchoate** [prebid/prebid-cache#36]
I understand that the GET method for prebid-cache should be publicly accessible, but there's no reason that the POST method should be public. Some mechanism to secure the POST method needs to be added to prevent abuse.

Currently, anyone can write to the Appnexus prebid-cache instance, since it doesn't require any kind of access key to POST:

```
curl -X "POST" "https://prebid.adnxs.com/pbc/v1/cache" \
     -H 'Content-Type: application/json' \
     -d $'{
  "puts": [
    {
      "type": "xml",
      "value": "<tag>Your XML content goes here!</tag>"
    },
    {
      "type": "json",
      "value": [
        1,
        true,
        "JSON value of any type can go here."
      ]
    }
  ]
}'
```

Expected result: a 400 error (Invalid request), since it should require an API key of some kind to be in the request.

Actual result: a 200 response, including the uuids issued for each element stored to the cache.

**Comment by dbemiller** [comment]
Hey! Thanks for the report.

I'm not clear on how an access key would help here. This endpoint is called from the client for standard `Prebid.js` video bidding... so it seems like a malicious user could just use dev tools to scrape the API key from the request of a legitimate page.

Not sure if I'm missing something?

**Comment by bradchoate** [comment]
From a quick review of the Prebid server adapter of Prebid.js, it appears to just use the GET service request as well. Public read without an API key is fine; public write isn’t.

**Comment by SyntaxNode** [comment]
I'm going to close this issue. PRs to add configurable access controls are welcomed. Our use cases haven't warranted it, so we haven't built it, but someone else certainly can.
