### ISSUE TITLE
Monitoring friendly index route

### ISSUE THREAD

**Issue by vamsiikrishna** [prebid/prebid-cache#43]
Hi,

when we open prebid-cache index route, it returns a 404 response. 
Most of the monitoring systems will treat a 404 response like a fail response and marks the application as down.

can we add a index page to display some message like the prebid-server does ?

We can just reuse this from README  : 

This application stores short-term data for use in Prebid. It exists to support Video Ads from Prebid.js, as well as prebid-native.

Thank you.

**Comment by dbemiller** [comment]
Yeah, feel free to make a PR for it if it helps you.

You could also just use the `/status` endpoint that exists today, if your monitoring infrastructure is configurable:

- https://github.com/prebid/prebid-cache/blob/master/endpoints/routing/handler.go#L20
- https://github.com/prebid/prebid-cache/blob/master/endpoints/status.go#L8
