### ISSUE TITLE
Potential race condition

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-cache#46]
It is possible that two requests will result in the same UUID key. Given how UUIDs are generated, this won't happen practically. But now we also have a PR in place to allow a key to be generated externally, which will only increase the possibility of a key collision. The key set code does check if a key already exists, so the window to overwrite is small, two parallel requests must both run the key exists check before either of them executes the key write function.

It behoves us to consider the potential consequences of the race condition hitting. The worst case of writing two pieces of data to the same location concurrently is having corrupted data stored in that location. However any backend worth using in production should prevent this, and leave us with one of the values stored intact, and the other value(s) discarded. So corrupt data should not be a concern.

So the real concern with this issue is having the wrong payload stored under a key, from the perspective of a particular user of cache. I see two vectors where this can happen with any frequency.
1) A bad actor is sniffing traffic to the cache server, and is pushing malicious content into the cache under the same key as a legitimate app.
2) A poorly coded app is using the set key feature, but not choosing keys unique enough to avoid key collisions in practice.

1) requires sniffing traffic and generating cache requests in real time, which will hit the cache server at the same time as the initial request. (If the bad actor can conduct a man-in-the-middle attack in order to sync up the initial request and the duplicate key request, they already have a better attack vector than this issue provides) It is a daunting feat, but perhaps not impossible. If such an attack were to take place, due to latency factors and others out of the attackers control, the "replacement" payloads would have a 50% chance of landing before the intended payload. Also given network latency noise is much greater than the race condition window, in almost every case the app will get a failed to cache message rather than a successful cache response, so the attack will be very noticeable and still fail to succeed in nearly all attempts unless the app is poorly coded to ignore the cache return value and just assumes a successful store was done.

2) Given that network latencies have an order of magnitude more noise that the race window, nearly all collisions will hit a failed to cache condition rather than a successful return + overwrite. So again, only poorly coded apps that do not check the cache return values will suffer from this race condition.

Fixing this race condition would have to be done in the backend modules, to make "check for key + write value" into an atomic operation. Not all backends may support such functionality, and thus not be fixable. The result of fixing it is we will always return a failure message and never overwrite (rather than only doing it for 99.9% of the time). So even if we fix the issue, the poorly written apps that might suffer from the race condition will continue to suffer.

Given all this, it does not seem worth fixing. It is worth recording so people remain aware of it, and as a warning to app writers to not write poorly coded apps. :)

**Comment by hhhjort** [comment]
I have come up with a solution that can be done outside of the backend code, and thus does not depend on the backends supporting any particular feature. Add a map of "in flight" IDs using `sync/atomic` library to handle atomic operations on this datastore. In the put handler, register a new entry into this datastructure for each new key it needs to store. Once registered, so a key exists check if necessary and then a key store. Once that is done, unregister the key. If the key already exists when attempting to register a key, we have a key collision and the process attempting to register the key can move on to returning the failure message.

This would be a large performance hit and likely not worth the effort.

**Comment by dbemiller** [comment]
That would only work if you're running a single PBC instance. Not if you have more than one instance + a load balancer.

**Comment by SyntaxNode** [comment]
> Fixing this race condition would have to be done in the backend modules, to make "check for key + write value" into an atomic operation.

This has been implemented. @guscarreon updated all backends to support atomic key check / write operations. Data corruption is no longer possible. The data race "winner" will get a positive response and the "loser" will get a duplicate key error.
