### ISSUE TITLE
No LICENSE chosen for this project

### ISSUE THREAD

**Issue by egreaves** [prebid/prebid-cache#49]
I noticed there is no LICENSE file in this project, while [prebid-server](https://github.com/prebid/prebid-server/blob/master/LICENSE) has the Apache License 2.0. Is there a plan to include a license file? Otherwise, folks interested in forking this project have to assume the default [github license](https://help.github.com/en/articles/licensing-a-repository#choosing-the-right-license), which is quite restrictive.

**Comment by mkendall07** [comment]
it should have the same apache License. Thanks for pointing it out. We will add it.

**Comment by egreaves** [comment]
@mkendall07 thanks for the quick response! Feel free to ping me whenever this is in place.
