### ISSUE TITLE
Default settings result in unacceptable combination of CORS response headers

### ISSUE THREAD

**Issue by PubMatic-OpenWrap** [prebid/prebid-cache#59]
By default, the CORS object in prebid-cache is initialised as follows with AllowCredentials set to true:

`coresCfg := cors.New(cors.Options{AllowCredentials: true})`

Due to this, when the Origin request header is passed, for example `http://foo/bar`, then prebid-cache end-points return the following response headers:

`Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true`

This results in a CORS error: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’

Ideally, the response header should contain the Origin value from the request header, in this case: `http://foo/bar`. The CORS module should generate the correct combination of headers by default.

**Comment by PubMatic-OpenWrap** [comment]
#60

**Comment by mansinahar** [comment]
Closing this since the fix was merged. Please re-open if the issue still persists.
