### ISSUE TITLE
Wrong counter names

### ISSUE THREAD

**Issue by ix-prebid-support** [prebid/prebid-cache#74]
If I'm not mistaken, these two counter names must be swapped:

https://github.com/prebid/prebid-cache/blob/282ec907e616c3a7d49e903249b8595b7ac12922/metrics/prometheus/prometheus.go#L124
https://github.com/prebid/prebid-cache/blob/282ec907e616c3a7d49e903249b8595b7ac12922/metrics/prometheus/prometheus.go#L125

**Comment by guscarreon** [comment]
Good catch @ix-prebid-support, thanks for pointing this out. Posted pull request #79 to fix this.
